CREATE TABLE USER{
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    USER_PHONE VARCHAR(50) NOT NULL,
    USER_ADDRESS VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    USER_ROLE VARCHAR(50) NOT NULL,
    USER_STATE VARCHAR(50) NOT NULL,
    USER_IMAGE VARCHAR(50) NOT NULL,
    PRIMARY KEY (USER_ID)
    FOREIGN KEY (USER_ROLE) REFERENCES ROLE(USER_ID)
};

CREATE TABLE ROLE{
    ROLE_ID INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    PRIMARY KEY (ROLE_ID)
};

CREATE TABLE STORE{
    STORE_ID INT NOT NULL AUTO_INCREMENT,
    STORE_NAME VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    STORE_ADDRESS VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    STORE_PHONE VARCHAR(50) NOT NULL,
    STORE_EMAIL VARCHAR(50) NOT NULL,
    STORE_DESCRIPTION VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    STORE_IMAGE VARCHAR(50) NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (STORE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
};

CREATE TABLE BRAND{
    BRAND_ID INT NOT NULL AUTO_INCREMENT,
    BRAND_NAME VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    PRIMARY KEY (BRAND_ID)
};

CREATE TABLE CATEGORY{
    CATALOG_ID INT NOT NULL AUTO_INCREMENT,
    CATALOG_NAME VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    CATALOG_IMAGE VARCHAR(50) NOT NULL,
    NUMBER_PRODUCT INT NOT NULL,
    CATALOG_DESCRIPTION VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    PRIMARY KEY (CATALOG_ID)
};

CREATE TABLE PRODUCT{
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    PRODUCT_PRICE INT NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    PRODUCT_IMAGE VARCHAR(50) NOT NULL,
    CATALOG_ID INT NOT NULL,
    BRAND_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (CATALOG_ID) REFERENCES CATALOG(CATALOG_ID)
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID)
};

-- THUỘC TÍNH SẢN PHẨM
CREATE TABLE PRODUCT_QUANTITY{ 
    PRODUCT_ID INT NOT NULL,
    PRODUCT_QUANTIRY INT NOT NULL,
    PRODUCT_SALEPRICE INT NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
};

CREATE TABLE PROMOTION{
    PROMOTION_ID INT NOT NULL AUTO_INCREMENT,
    PROMOTION_NAME VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    PROMOTION_STARTDATE DATE NOT NULL,
    PROMOTION_ENDDATE DATE NOT NULL,
    PROMOTION_PERCENT INT NOT NULL,
    PRIMARY KEY (PROMOTION_ID)
};

CREATE TABLE ORDER{
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_DATE DATE NOT NULL,
    ORDER_TOTAL INT NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
};

CREATE TABLE ORDER_DETAIL{
    ORDER_DETAIL_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_DETAIL_QUANTITY INT NOT NULL,
    ORDER_DETAIL_PRICE INT NOT NULL,
    ORDERD_ETAIL_STATUS VARCHAR(50) NOT NULL,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (ORDERDETAIL_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER(ORDER_ID)
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
};

CREATE TABLE REVENUE{
    REVENUE_ID INT NOT NULL AUTO_INCREMENT,
    REVENUE_DATE DATE NOT NULL,
    REVENUE_TOTAL INT NOT NULL,
    PRIMARY KEY (REVENUE_ID)
};


CREATE TABLE FEEDBACK{
    FEEDBACK_ID INT NOT NULL AUTO_INCREMENT,
    FEEDBACK_CONTENT VARCHAR(50) NOT NULL CHARACTER SET utf8 COLLATE utf8_general_ci,
    FEEDBACK_DATE DATE NOT NULL,
    FEEDBACK_STATUS VARCHAR(50) NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (FEEDBACK_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
};

CREATE TABLE SITE_TRAFFIC{
    traffic_DATE DATE NOT NULL,
    webTraffic INT NOT NULL,
    buyTraffic INT NOT NULL,
    traffic_TOTAL INT NOT NULL,
    PRIMARY KEY (traffic_ID)
};

--------------
-- Data
--------------
-- Path: libraries/data.sql












