CREATE TABLE ROLES(
    ROLE_ID INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL, 
    PRIMARY KEY (ROLE_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

insert into ROLES(ROLE_NAME) values('admin');
insert into ROLES(ROLE_NAME) values('user');

CREATE TABLE USERS(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(50),
    USER_EMAIL VARCHAR(50),
    USER_PHONE VARCHAR(50) NOT NULL,
    USER_ADDRESS VARCHAR(50),
    USER_ROLE int NOT NULL,
    USER_STATE VARCHAR(50) NOT NULL,
    USER_IMAGE VARCHAR(100),
    CREATE_DATE DATE NOT NULL,
    LAST_LOGIN DATE NOT NULL,
    PRIMARY KEY (USER_ID, USER_PHONE),
    FOREIGN KEY (USER_ID) REFERENCES ROLES(ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

insert into USERS(USER_NAME, USER_PASSWORD, USER_EMAIL, USER_PHONE, USER_ROLE, USER_STATE, CREATE_DATE, LAST_LOGIN) 
            values('admin', null, null, +84359297916, 1, 'active', '2020-11-30', '2020-11-30');


CREATE TABLE STORE(
    STORE_ID INT NOT NULL AUTO_INCREMENT,
    STORE_NAME VARCHAR(50) NOT NULL ,
    STORE_ADDRESS VARCHAR(50) NOT NULL ,
    STORE_PHONE VARCHAR(50) NOT NULL,
    STORE_EMAIL VARCHAR(50) NOT NULL,
    STORE_DESCRIPTION VARCHAR(50) NOT NULL ,
    STORE_IMAGE VARCHAR(100) NOT NULL,
    PRIMARY KEY (STORE_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE BRANDS(
    BRAND_ID INT NOT NULL AUTO_INCREMENT,
    BRAND_NAME VARCHAR(50) NOT NULL ,
    CONTRY VARCHAR(50) NOT NULL ,
    BRAND_IMAGE VARCHAR(50) NOT NULL,
    NUMBER_PRODUCT INT NOT NULL,
    BRAND_DESCRIPTION VARCHAR(50) NOT NULL ,
    PRIMARY KEY (BRAND_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CATEGORIES(
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50) NOT NULL ,
    CATEGORY_IMAGE VARCHAR(50) NOT NULL,
    NUMBER_PRODUCT INT NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(50) NOT NULL ,
    PRIMARY KEY (CATEGORY_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Tivi', 'https://cdn.tgdd.vn/Products/Images/1942/235794/led-4k-samsung-ua65au8100-2.jpg', 0, 'Television');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Loa, dàn karaoke', 'https://cdn.tgdd.vn/Products/Images/2162/304779/304779-600x600.jpg', 0, 'Audio and Karaoke System');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy giặt', 'https://cdn.tgdd.vn/Products/Images/1944/304621/may-giat-say-lg-inverter-21-kg-f2721hvrb-110423-020146-600x600.jpg', 0, 'Washing Machine');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy sấy', 'https://cdn.tgdd.vn/Products/Images/2202/309558/may-say-bom-nhiet-samsung-9-kg-dv90bb9440gh-sv-230623-122345-600x600.jpg', 0, 'Dryer');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy lạnh', 'https://cdn.tgdd.vn/Products/Images/2002/303862/Slider/may-lanh-aqua-inverter-1-hp-aqa-ruv10rb638174355437648592.jpg', 0, 'Air Conditioner');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Tủ lạnh', 'https://cdn.tgdd.vn/Products/Images/1943/220325/Slider/02-1020x571.jpg', 0, 'Refrigerator');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy nước nóng', 'https://cdn.tgdd.vn/Products/Images/1962/227136/Slider/rossi-elegenz-20l-ngang-rez20sl-180821-0947041.jpg', 0, 'Water Heater');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy xay, máy ép', 'https://cdn.tgdd.vn/Products/Images/1985/278366/tefal-blendforce-piano-bl47yb66-1.jpg', 0, 'Grinder and Press');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy lọc nước', 'https://cdn.tgdd.vn/Products/Images/3385/296831/may-loc-nuoc-ro-karofi-kaq-x16-10-loi-1.jpg', 0, 'Water Filter');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy hút bụi', 'https://cdn.tgdd.vn/Products/Images/1990/310455/may-hut-bui-lau-nha-dreame-h12-dual-1.jpg', 0, 'Vacuum Cleaner');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy rửa chén', 'https://cdn.tgdd.vn/Products/Images/5475/299889/may-rua-chen-bosch-sms46gi01p-tgb-1-1.jpg', 0, 'Dishwasher');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Lò nướng', 'https://cdn.tgdd.vn/Products/Images/2063/291407/lo-nuong-electrolux-eot4022xfg-40-lit-2.jpg', 0, 'Oven');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Thiết bị nhà bếp', 'https://cdn.tgdd.vn/Products/Images/12318/234363/electrolux-e2ts1-100w-090223-111132-600x600.jpgg', 0, 'Kitchen Appliances');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Quạt', 'https://cdn.tgdd.vn/Products/Images/7498/236964/daikiosan-dka-04000g-040923-025222-600x600.jpg', 0, 'Fan');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Máy lọc không khí', 'https://cdn.tgdd.vn/Products/Images/5473/243091/243091-600x600.jpg', 0, 'Air Purifier');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Bếp', 'https://cdn.tgdd.vn/Products/Images/1982/279966/279966-600x600.jpg', 0, 'Stove');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Thiết bị sưởi ấm', 'https://cdn.tgdd.vn/Products/Images/2428/252133/gom-kangaroo-kgfh05-1.-600x600.jpg', 0, 'Thiết bị sưởi ấm');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Nồi', 'https://cdn.tgdd.vn/Products/Images/1922/147243/delites-ncr1502-281022-033255-600x600.jpg', 0, 'Pot');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Cây nước nóng lạnh', 'https://cdn.tgdd.vn/Products/Images/2222/210643/210643-1--600x600.jpg', 0, 'Hot and Cold Water Dispenser');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_IMAGE, NUMBER_PRODUCT, CATEGORY_DESCRIPTION) 
    VALUES ('Điện thoại', 'https://cdn.tgdd.vn/Products/Images/42/235838/Galaxy-S22-Ultra-Burgundy-600x600.jpg', 0, 'Phone');

CREATE TABLE PRODUCTS(
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL ,
    PRODUCT_DESCRIPTION VARCHAR(50) NOT NULL ,
    PRODUCT_IMAGE VARCHAR(50) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    BRAND_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE PROMOTION(
    PROMOTION_ID INT NOT NULL AUTO_INCREMENT,
    PROMOTION_NAME VARCHAR(50) NOT NULL ,
    PROMOTION_CODE VARCHAR(50) NOT NULL,
    PROMOTION_STARTDATE DATE NOT NULL,
    PROMOTION_ENDDATE DATE NOT NULL,
    PROMOTION_PERCENT INT NOT NULL,
    PRIMARY KEY (PROMOTION_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BIẾN THỂ SẢN PHẨM
CREATE TABLE PRODUCT_VARIANT( 
    PRODUCT_VARIANT_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_VARIANT_NAME VARCHAR(50) , -- không có biến thể thì để null
    PRODUCT_ID INT NOT NULL,
    PRODUCT_QUANTITY INT NOT NULL,
    PRODUCT_SALEPRICE INT NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(50) NOT NULL ,
    PRODUCT_IMAGE VARCHAR(50) NOT NULL,
    PRIMARY KEY (PRODUCT_VARIANT_ID, PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE ORDERS(
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_DATE DATE NOT NULL,
    ORDER_TOTAL INT NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL, --Khởi tạo, Đang giao, Đã giao, Đã hủy
    USER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ORDER_DETAILS(
    ORDER_DETAIL_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_DETAIL_QUANTITY INT NOT NULL,
    ORDER_DETAIL_PRICE INT NOT NULL,
    ORDERD_DETAIL_STATUS VARCHAR(50) NOT NULL,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (ORDER_DETAIL_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE REVENUE(
    REVENUE_ID INT NOT NULL AUTO_INCREMENT,
    REVENUE_DATE DATE NOT NULL,
    REVENUE_TOTAL INT NOT NULL,
    PRIMARY KEY (REVENUE_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE FEEDBACK(
    FEEDBACK_ID INT NOT NULL AUTO_INCREMENT,
    FEEDBACK_CONTENT VARCHAR(50) NOT NULL ,
    FEEDBACK_DATE DATE NOT NULL,
    FEEDBACK_STATUS VARCHAR(50) NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (FEEDBACK_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE SITE_TRAFFIC(
    traffic_ID int AUTO_INCREMENT,
    traffic_DATE DATE NOT NULL,
    webTraffic INT NOT NULL,
    buyTraffic INT NOT NULL,
    traffic_TOTAL INT NOT NULL,
    PRIMARY KEY (traffic_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE WARRANTY(
    WARRANTY_ID INT NOT NULL AUTO_INCREMENT,
    CREATE_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    WARRANTY_STATUS VARCHAR(50) NOT NULL,
    ORDER_DETAIL_ID INT NOT NULL,
    PRIMARY KEY (WARRANTY_ID),
    FOREIGN KEY (ORDER_DETAIL_ID) REFERENCES ORDER_DETAILS(ORDER_DETAIL_ID)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


------------- TRIGGER
-- Trigger to update NUMBER_PRODUCT in BRAND table
DELIMITER //

CREATE TRIGGER update_brand_product_count
AFTER INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
    UPDATE BRAND
    SET NUMBER_PRODUCT = NUMBER_PRODUCT + 1
    WHERE BRAND_ID = NEW.BRAND_ID;
END;
//

-- Trigger to update NUMBER_PRODUCT in CATEGORY table
CREATE TRIGGER update_category_product_count
AFTER INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
    UPDATE CATEGORY
    SET NUMBER_PRODUCT = NUMBER_PRODUCT + 1
    WHERE CATEGORY_ID = NEW.CATEGORY_ID;
END;
//

DELIMITER ;


--------------
-- Data
--------------
-- Path: libraries/data.sql
